/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-07 at 20:06:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.profrate_1148.profrateAPI.model;

/**
 * Model definition for ProfrateRateRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the profrateAPI. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ProfrateRateRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("knowledge_level")
  private java.lang.Double knowledgeLevel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double personality;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("research_skill")
  private java.lang.Double researchSkill;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("teaching_skill")
  private java.lang.Double teachingSkill;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ProfrateRateRequest setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getKnowledgeLevel() {
    return knowledgeLevel;
  }

  /**
   * @param knowledgeLevel knowledgeLevel or {@code null} for none
   */
  public ProfrateRateRequest setKnowledgeLevel(java.lang.Double knowledgeLevel) {
    this.knowledgeLevel = knowledgeLevel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getPersonality() {
    return personality;
  }

  /**
   * @param personality personality or {@code null} for none
   */
  public ProfrateRateRequest setPersonality(java.lang.Double personality) {
    this.personality = personality;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getResearchSkill() {
    return researchSkill;
  }

  /**
   * @param researchSkill researchSkill or {@code null} for none
   */
  public ProfrateRateRequest setResearchSkill(java.lang.Double researchSkill) {
    this.researchSkill = researchSkill;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getTeachingSkill() {
    return teachingSkill;
  }

  /**
   * @param teachingSkill teachingSkill or {@code null} for none
   */
  public ProfrateRateRequest setTeachingSkill(java.lang.Double teachingSkill) {
    this.teachingSkill = teachingSkill;
    return this;
  }

  @Override
  public ProfrateRateRequest set(String fieldName, Object value) {
    return (ProfrateRateRequest) super.set(fieldName, value);
  }

  @Override
  public ProfrateRateRequest clone() {
    return (ProfrateRateRequest) super.clone();
  }

}
