/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-07 at 05:02:34 UTC 
 * Modify at your own risk.
 */

package com.appspot.profrate_1148.profrateAPI.model;

/**
 * Model definition for ProfrateCommentReplyResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the profrateAPI. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ProfrateCommentReplyResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("comment_reply")
  private ProfrateCommentReplyMessage commentReply;

  /**
   * @return value or {@code null} for none
   */
  public ProfrateCommentReplyMessage getCommentReply() {
    return commentReply;
  }

  /**
   * @param commentReply commentReply or {@code null} for none
   */
  public ProfrateCommentReplyResponse setCommentReply(ProfrateCommentReplyMessage commentReply) {
    this.commentReply = commentReply;
    return this;
  }

  @Override
  public ProfrateCommentReplyResponse set(String fieldName, Object value) {
    return (ProfrateCommentReplyResponse) super.set(fieldName, value);
  }

  @Override
  public ProfrateCommentReplyResponse clone() {
    return (ProfrateCommentReplyResponse) super.clone();
  }

}
